# Generated by Django 4.2.11 on 2025-03-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('file_name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('word', 'file_name')},
            },
        ),
    ]
